#include "../MixedFilament.hpp"
#include "Internal.hpp"

#include <algorithm>
#include <cmath>
#include <numeric>
#include <sstream>

namespace Slic3r {

using namespace MixedFilamentInternal;

std::optional<MixedFilamentPhysicalRef> MixedFilamentWeightedBlend::component_a() const
{
    return components.empty() ? std::nullopt : std::optional<MixedFilamentPhysicalRef>(components.front().filament);
}

std::optional<MixedFilamentPhysicalRef> MixedFilamentWeightedBlend::component_b() const
{
    return components.size() < 2 ? std::nullopt : std::optional<MixedFilamentPhysicalRef>(components[1].filament);
}

unsigned int MixedFilamentWeightedBlend::component_a_id(unsigned int fallback) const
{
    const std::optional<MixedFilamentPhysicalRef> ref = component_a();
    return ref && ref->id != 0 ? ref->id : fallback;
}

unsigned int MixedFilamentWeightedBlend::component_b_id(unsigned int fallback) const
{
    const std::optional<MixedFilamentPhysicalRef> ref = component_b();
    return ref && ref->id != 0 ? ref->id : fallback;
}

int MixedFilamentWeightedBlend::component_b_percent() const
{
    return components.size() < 2 ? 50 : std::clamp(components[1].percent, 0, 100);
}

namespace {

MixedFilamentWeightedBlend pair_blend_from_components(unsigned int component_a, unsigned int component_b, int component_b_percent)
{
    const int pct_b = std::clamp(component_b_percent, 0, 100);
    return {{{{component_a}, 100 - pct_b}, {{component_b}, pct_b}}};
}

MixedFilamentLegacyPair legacy_pair_from_blend(const MixedFilamentWeightedBlend& blend)
{
    return MixedFilamentLegacyPair{{blend.component_a_id(1)}, {blend.component_b_id(2)}};
}

MixedFilamentWeightedBlend aggregate_blend_from_manual_pattern(const MixedFilamentManualPattern& pattern,
                                                               const MixedFilamentWeightedBlend& fallback)
{
    std::vector<unsigned int> ordered_ids;
    std::vector<int>          counts;
    for (const std::vector<MixedFilamentPhysicalRef>& group : pattern.groups) {
        for (const MixedFilamentPhysicalRef& ref : group) {
            if (ref.id == 0)
                continue;
            auto it = std::find(ordered_ids.begin(), ordered_ids.end(), ref.id);
            if (it == ordered_ids.end()) {
                ordered_ids.emplace_back(ref.id);
                counts.emplace_back(1);
            } else {
                ++counts[size_t(std::distance(ordered_ids.begin(), it))];
            }
        }
    }

    if (ordered_ids.empty())
        return fallback;

    const std::vector<int> percents = normalize_weight_vector_to_percent(counts);
    MixedFilamentWeightedBlend out;
    out.components.reserve(ordered_ids.size());
    for (size_t i = 0; i < ordered_ids.size(); ++i)
        out.components.push_back({{ordered_ids[i]}, percents[i]});
    return out;
}

} // namespace

MixedFilamentDefinition mixed_filament_definition_from_legacy_row(const MixedFilamentLegacyRow& row, size_t)
{
    MixedFilamentDefinition definition;

    definition.identity.stable_id = row.stable_id;

    definition.source.kind        = row.custom ? MixedFilamentSourceKind::Custom : MixedFilamentSourceKind::AutoGenerated;
    definition.source.origin_auto = row.origin_auto;

    definition.visibility.tombstoned = row.deleted;

    const MixedFilamentWeightedBlend legacy_pair_blend = pair_blend_from_components(row.component_a, row.component_b, row.mix_b_percent);
    definition.recipe.manual_pattern              = mixed_filament_manual_pattern_from_legacy_row(row);
    const std::optional<MixedFilamentWeightedBlend> legacy_weighted_blend = mixed_filament_weighted_blend_from_legacy_row(row);

    if (definition.recipe.manual_pattern) {
        definition.recipe.kind = MixedFilamentRecipeKind::ManualPattern;
        definition.recipe.blend =
            legacy_weighted_blend.value_or(aggregate_blend_from_manual_pattern(*definition.recipe.manual_pattern, legacy_pair_blend));
    } else {
        definition.recipe.kind = MixedFilamentRecipeKind::WeightedBlend;
        definition.recipe.blend = legacy_weighted_blend.value_or(legacy_pair_blend);
    }

    definition.behavior.distribution = mixed_filament_distribution_from_legacy_mode(row.distribution_mode, row.gradient_component_ids);
    definition.behavior.layer_cadence.component_a_layers   = row.ratio_a;
    definition.behavior.layer_cadence.component_b_layers   = row.ratio_b;
    definition.behavior.local_z.max_sublayers              = row.local_z_max_sublayers;
    definition.behavior.surface_bias.component_a_offset_mm = row.component_a_surface_offset;
    definition.behavior.surface_bias.component_b_offset_mm = row.component_b_surface_offset;

    definition.presentation.display_color = row.display_color;

    return definition;
}

void apply_mixed_filament_definition_to_legacy_row(const MixedFilamentDefinition& definition, MixedFilamentLegacyRow& row)
{
    const MixedFilamentLegacyPair pair = legacy_pair_from_blend(definition.recipe.blend);

    row.component_a                = pair.component_a.id;
    row.component_b                = pair.component_b.id;
    row.stable_id                  = definition.identity.stable_id;
    row.ratio_a                    = std::max(0, definition.behavior.layer_cadence.component_a_layers);
    row.ratio_b                    = std::max(0, definition.behavior.layer_cadence.component_b_layers);
    row.mix_b_percent              = definition.recipe.blend.component_b_percent();
    row.distribution_mode          = legacy_distribution_mode_from_mixed_filament_distribution(definition.behavior.distribution);
    row.local_z_max_sublayers      = std::max(0, definition.behavior.local_z.max_sublayers);
    row.component_a_surface_offset = definition.behavior.surface_bias.component_a_offset_mm;
    row.component_b_surface_offset = definition.behavior.surface_bias.component_b_offset_mm;
    row.deleted                    = definition.visibility.tombstoned;
    row.enabled                    = !row.deleted;
    row.custom        = definition.source.kind == MixedFilamentSourceKind::Custom;
    row.origin_auto   = definition.source.origin_auto;
    row.display_color = definition.presentation.display_color;

    row.manual_pattern.clear();
    row.gradient_component_ids.clear();
    row.gradient_component_weights.clear();

    if (definition.recipe.manual_pattern) {
        row.manual_pattern = legacy_manual_pattern_from_mixed_filament_pattern(*definition.recipe.manual_pattern, pair);
        if (!row.manual_pattern.empty())
            row.mix_b_percent = mix_percent_from_normalized_pattern(row.manual_pattern);
        if (definition.behavior.distribution == MixedFilamentDistributionMode::LayerCycle && definition.recipe.blend.components.size() >= 3)
            apply_mixed_filament_blend_to_legacy_row(definition.recipe.blend, row);
    } else if (definition.recipe.blend.components.size() >= 3) {
        apply_mixed_filament_blend_to_legacy_row(definition.recipe.blend, row);
    }
}

MixedFilamentLegacyRow mixed_filament_legacy_row_from_definition(const MixedFilamentDefinition& definition)
{
    MixedFilamentLegacyRow row;
    apply_mixed_filament_definition_to_legacy_row(definition, row);
    return row;
}

std::optional<MixedFilamentManualPattern> mixed_filament_manual_pattern_from_string(const std::string& pattern,
                                                                                    unsigned int       component_a,
                                                                                    unsigned int       component_b,
                                                                                    size_t             num_physical)
{
    const std::string normalized = MixedFilamentManager::normalize_manual_pattern(pattern);
    if (normalized.empty())
        return std::nullopt;

    const MixedFilamentLegacyPair pair{{component_a}, {component_b}};
    MixedFilamentManualPattern    out;
    for (const std::string& group : split_manual_pattern_groups(normalized)) {
        std::vector<MixedFilamentPhysicalRef> refs;
        refs.reserve(group.size());
        for (const char token : group) {
            const unsigned int id = physical_filament_from_legacy_pattern_token(token, pair);
            if (id >= 1 && (num_physical == 0 || id <= num_physical))
                refs.push_back({id});
        }
        if (!refs.empty())
            out.groups.emplace_back(std::move(refs));
    }

    return out.groups.empty() ? std::nullopt : std::optional<MixedFilamentManualPattern>(std::move(out));
}

std::string mixed_filament_manual_pattern_string(const MixedFilamentDefinition& definition)
{
    if (!definition.recipe.manual_pattern)
        return {};

    return legacy_manual_pattern_from_mixed_filament_pattern(*definition.recipe.manual_pattern,
                                                            legacy_pair_from_blend(definition.recipe.blend));
}

static bool physical_ref_is_valid(const MixedFilamentPhysicalRef& ref, size_t num_physical)
{
    return ref.id >= 1 && (num_physical == 0 || ref.id <= num_physical);
}

std::vector<unsigned int> mixed_filament_manual_pattern_sequence(const MixedFilamentDefinition& definition, size_t num_physical)
{
    std::vector<unsigned int> sequence;
    if (!definition.recipe.manual_pattern)
        return sequence;

    for (const std::vector<MixedFilamentPhysicalRef>& group : definition.recipe.manual_pattern->groups) {
        sequence.reserve(sequence.size() + group.size());
        for (const MixedFilamentPhysicalRef& ref : group)
            if (physical_ref_is_valid(ref, num_physical))
                sequence.emplace_back(ref.id);
    }
    return sequence;
}

std::vector<unsigned int> mixed_filament_manual_pattern_preview_sequence(const MixedFilamentDefinition& definition,
                                                                         size_t                         num_physical,
                                                                         size_t                         wall_loops)
{
    std::vector<unsigned int> sequence;
    if (!definition.recipe.manual_pattern || num_physical == 0)
        return sequence;

    const auto& groups = definition.recipe.manual_pattern->groups;
    if (groups.empty())
        return sequence;

    if (groups.size() == 1) {
        sequence.reserve(groups.front().size());
        for (const MixedFilamentPhysicalRef& ref : groups.front())
            if (physical_ref_is_valid(ref, num_physical))
                sequence.emplace_back(ref.id);
        return sequence;
    }

    constexpr size_t k_max_preview_cycle = 48;
    size_t           cycle               = 1;
    for (const std::vector<MixedFilamentPhysicalRef>& group : groups) {
        if (group.empty())
            continue;
        cycle = std::lcm(cycle, group.size());
        if (cycle >= k_max_preview_cycle) {
            cycle = k_max_preview_cycle;
            break;
        }
    }

    const size_t preview_wall_loops = std::max<size_t>(1, wall_loops == 0 ? groups.size() : wall_loops);
    sequence.reserve(preview_wall_loops * cycle);
    for (size_t layer_idx = 0; layer_idx < cycle; ++layer_idx) {
        for (size_t wall_idx = 0; wall_idx < preview_wall_loops; ++wall_idx) {
            const auto& group = groups[std::min(wall_idx, groups.size() - 1)];
            if (group.empty())
                continue;
            const MixedFilamentPhysicalRef& ref = group[layer_idx % group.size()];
            if (physical_ref_is_valid(ref, num_physical))
                sequence.emplace_back(ref.id);
        }
    }

    return sequence;
}

std::vector<unsigned int> mixed_filament_blend_component_ids(const MixedFilamentDefinition& definition, size_t num_physical)
{
    std::vector<unsigned int> ids;
    ids.reserve(definition.recipe.blend.components.size());
    for (const MixedFilamentWeightedComponent& component : definition.recipe.blend.components)
        if (physical_ref_is_valid(component.filament, num_physical))
            ids.emplace_back(component.filament.id);
    return ids;
}

std::vector<int> mixed_filament_blend_component_weights(const MixedFilamentDefinition& definition)
{
    std::vector<int> weights;
    weights.reserve(definition.recipe.blend.components.size());
    for (const MixedFilamentWeightedComponent& component : definition.recipe.blend.components)
        weights.emplace_back(std::max(0, component.percent));
    return weights;
}

std::vector<unsigned int> mixed_filament_weighted_blend_sequence(const MixedFilamentDefinition& definition, size_t num_physical)
{
    const std::vector<unsigned int> ids = mixed_filament_blend_component_ids(definition, num_physical);
    if (ids.empty())
        return {};

    std::vector<int> weights = mixed_filament_blend_component_weights(definition);
    if (weights.size() != ids.size())
        weights.assign(ids.size(), 1);
    return build_weighted_gradient_sequence(ids, weights);
}

// ---------------------------------------------------------------------------
// MixedFilamentManager
// ---------------------------------------------------------------------------

} // namespace Slic3r
