#!/usr/bin/env python3
"""Extract the ICC Munsell polynomial estimator into a C++ data header."""

from __future__ import annotations

import argparse
import hashlib
import pathlib
import struct


SOURCE_URL = "https://www.color.org/resources/spectral/xyz2PolyEstimateRefV2.icc"
SOURCE_SHA256 = "8291983ea02ca7b7adf023a1f3ddd3fc618a853ef20ffd01eb145504a92ff2e4"
PROFILE_ID = "5436fbfce5f7414dc520bb6e5d9c1516"
INPUT_TERMS = 20
PROFILE_SAMPLES = 41
PROFILE_FIRST_NM = 380
OUTPUT_FIRST_NM = 400
OUTPUT_LAST_NM = 700
OUTPUT_STEP_NM = 10


def _tag_payload(profile: bytes, signature: bytes) -> bytes:
    if len(profile) < 132:
        raise ValueError("ICC profile is shorter than its tag table header")

    tag_count = struct.unpack_from(">I", profile, 128)[0]
    for index in range(tag_count):
        entry = 132 + 12 * index
        if entry + 12 > len(profile):
            raise ValueError("ICC tag table is truncated")
        tag_signature, offset, size = struct.unpack_from(">4sII", profile, entry)
        if tag_signature == signature:
            if offset + size > len(profile):
                raise ValueError(f"ICC tag {signature!r} extends beyond the profile")
            return profile[offset : offset + size]
    raise ValueError(f"ICC profile does not contain tag {signature!r}")


def _extract_matrix(profile: bytes) -> list[list[float]]:
    b_to_a = _tag_payload(profile, b"B2A3")
    matrix_offset = b_to_a.find(b"matf")
    if matrix_offset < 0 or matrix_offset + 12 > len(b_to_a):
        raise ValueError("BToA3 does not contain a matrix-float element")

    input_channels, output_channels = struct.unpack_from(">HH", b_to_a, matrix_offset + 8)
    if (input_channels, output_channels) != (INPUT_TERMS, PROFILE_SAMPLES):
        raise ValueError(
            "Unexpected ICC polynomial dimensions: "
            f"{input_channels} inputs, {output_channels} outputs"
        )

    value_count = input_channels * output_channels
    values_offset = matrix_offset + 12
    values_size = 4 * value_count
    if values_offset + values_size > len(b_to_a):
        raise ValueError("ICC polynomial matrix is truncated")

    values = struct.unpack_from(f">{value_count}f", b_to_a, values_offset)
    return [
        list(values[row * input_channels : (row + 1) * input_channels])
        for row in range(output_channels)
    ]


def _format_float(value: float) -> str:
    # Nine significant digits round-trip every source float32 coefficient.
    text = f"{value:.9g}"
    if "e" not in text and "." not in text:
        text += ".0"
    return text + "f"


def _render_header(matrix: list[list[float]]) -> str:
    first_row = (OUTPUT_FIRST_NM - PROFILE_FIRST_NM) // OUTPUT_STEP_NM
    sample_count = (OUTPUT_LAST_NM - OUTPUT_FIRST_NM) // OUTPUT_STEP_NM + 1
    selected = matrix[first_row : first_row + sample_count]
    if len(selected) != sample_count:
        raise ValueError("Requested wavelength range is outside the ICC profile")

    rows = []
    for row in selected:
        coefficients = [_format_float(value) for value in row]
        lines = []
        for start in range(0, len(coefficients), 5):
            line = "        " + ", ".join(coefficients[start : start + 5])
            if start + 5 < len(coefficients):
                line += ","
            lines.append(line)
        rows.append("    {{\n" + "\n".join(lines) + "\n    }}")

    return f"""// Generated by scripts/generate_full_spectrum_icc_polynomial_profile.py.
// Derived from ICC's Munsell Glossy D50 XYZ polynomial estimator profile.
// Source: {SOURCE_URL}
// Source SHA-256: {SOURCE_SHA256}
// ICC profile ID: {PROFILE_ID}
// Copyright 2022 International Color Consortium.
// Profile license: https://registry.color.org/profile-library/
#pragma once

#include <array>
#include <cstddef>

namespace Slic3r::FullSpectrumICCPolynomialProfileData {{

static constexpr std::size_t TERM_COUNT = {INPUT_TERMS};
static constexpr std::size_t SPECTRUM_SIZE = {sample_count};
static constexpr int FIRST_WAVELENGTH_NM = {OUTPUT_FIRST_NM};
static constexpr int LAST_WAVELENGTH_NM = {OUTPUT_LAST_NM};
static constexpr int WAVELENGTH_STEP_NM = {OUTPUT_STEP_NM};

static constexpr const char* SOURCE_PROFILE_SHA256 = "{SOURCE_SHA256}";
static constexpr const char* SOURCE_PROFILE_ID = "{PROFILE_ID}";
static constexpr const char* TRAINING_SET = "Munsell Glossy";
static constexpr const char* INPUT_COLORIMETRY = "D50 XYZ, CIE 1931 2 degree, Y=100";

// Term order:
// 1, X, Y, Z, X^2, Y^2, Z^2, XY, XZ, YZ, X^3, Y^3, Z^3,
// X^2Y, X^2Z, XY^2, XZ^2, Y^2Z, YZ^2, XYZ.
static constexpr std::array<std::array<float, TERM_COUNT>, SPECTRUM_SIZE> COEFFICIENTS = {{{{
{',\n'.join(rows)}
}}}};

}} // namespace Slic3r::FullSpectrumICCPolynomialProfileData
"""


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("profile", type=pathlib.Path, help="Downloaded xyz2PolyEstimateRefV2.icc")
    parser.add_argument("output", type=pathlib.Path, help="Generated C++ header path")
    args = parser.parse_args()

    profile = args.profile.read_bytes()
    declared_size = struct.unpack_from(">I", profile)[0] if len(profile) >= 4 else 0
    if declared_size != len(profile):
        raise SystemExit(
            f"Refusing ICC profile whose declared size is {declared_size}; actual size is {len(profile)}"
        )

    digest = hashlib.sha256(profile).hexdigest()
    if digest != SOURCE_SHA256:
        raise SystemExit(
            f"Refusing profile with SHA-256 {digest}; expected {SOURCE_SHA256}"
        )

    profile_id = profile[84:100].hex() if len(profile) >= 100 else ""
    if profile_id != PROFILE_ID:
        raise SystemExit(
            f"Refusing ICC profile ID {profile_id}; expected {PROFILE_ID}"
        )

    header = _render_header(_extract_matrix(profile))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(header, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
